# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: create release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set version env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/DocToIdoit.sln
    - name: Build Windows-x64
      run: dotnet publish src/DocToIdoit.sln -p:PublishProfile=Windows-X64 --no-restore
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r DocToIdoit-win-x64-${{ env.RELEASE_VERSION }}.zip src/DocToIdoit/bin/publish-win
    - uses: actions/upload-artifact@v2
      with:
        name: DocToIdoit-win-x64-${{ env.RELEASE_VERSION }}.zip
    - name: Build Linux-x64
      run: dotnet publish src/DocToIdoit.sln -p:PublishProfile=Linux-X64 --no-restore
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r DocToIdoit-linux-x64-${{ env.RELEASE_VERSION }}.zip src/DocToIdoit/bin/publish-linux
    - uses: actions/upload-artifact@v2
      with:
        name: DocToIdoit-linux-x64-${{ env.RELEASE_VERSION }}.zip
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Release files
        uses: softprops/action-gh-release@v1
        with:
          files: |
            DocToIdoit-win-x64-${{ env.RELEASE_VERSION }}.zip
            DocToIdoit-linux-x64-${{ env.RELEASE_VERSION }}.zip
